shoulder_hw_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: shoulder_hw_joint
    joint_speed: 0.2
    motor:
        id: 2
        init: 2048
        min: 0
        max: 4095

elbow_hw_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: elbow_hw_joint
    joint_speed: 0.2
    motor:
        id: 3
        init: 2048
        min: 0
        max: 4095

wrist_hw_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: wrist_hw_joint
    joint_speed: 0.2
    motor:
        id: 4
        init: 2048
        min: 0
        max: 4095

fingerjoint_hw_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: fingerjoint_hw_joint
    joint_speed: 0.2
    motor:
        id: 5
        init: 512
        min: 0
        max: 1023
